# Generated by Django 4.0.5 on 2022-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enc', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='faces/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
