# Generated by Django 4.0.5 on 2022-06-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_facesuser_delete_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facesuser',
            name='enc',
        ),
    ]
